In [176]:
import numpy as np
import pandas as pd
from sklearn.model_selection import cross_val_score

In [177]:
data= pd.read_csv("cars.csv")

In [178]:
data.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [179]:
data.isnull().sum().values.sum()

0

In [180]:
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [181]:
print(x.shape)
print(y.shape)

(32, 10)
(32,)


In [182]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20)

In [183]:
print(x_train.shape)
print(x_test.shape)

(25, 10)
(7, 10)


In [184]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [185]:
from sklearn.svm import SVC
classifier= SVC(kernel='linear', random_state= 0)
classifier.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

In [186]:
y_pred= classifier.predict(x_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

In [187]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
print("Accuracy score for SVM", accuracy_score(y_test,y_pred))

[[0 0 0 0 0]
 [1 2 0 0 0]
 [0 0 2 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]]
Accuracy score for SVM 0.5714285714285714


In [190]:
#Cross Validation
scores = cross_val_score(classifier, x_train, y_train, cv=3)
print(" Accuracy score for SVM using 10-fold cross validation: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

 Accuracy score for SVM using 10-fold cross validation: 0.60 (+/- 0.21)


In [191]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [192]:
y_pred= classifier.predict(x_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

In [193]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
print("Accuracy score for Random Forest", accuracy_score(y_test,y_pred))

[[3 0 0 0]
 [0 2 0 0]
 [0 1 0 0]
 [0 1 0 0]]
Accuracy score for Random Forest 0.7142857142857143


In [198]:
#Cross Validation
scores = cross_val_score(classifier, x_train, y_train, cv=2)
print(" Accuracy score for Random Forest using 10-fold cross validation: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

 Accuracy score for Random Forest using 10-fold cross validation: 0.55 (+/- 0.28)


In [199]:
  # KNN Model
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 2)
classifier.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=2)

In [200]:
y_pred= classifier.predict(x_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

In [201]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
print("Accuracy score for KNN", accuracy_score(y_test,y_pred))

[[0 0 0 0 0]
 [1 2 0 0 0]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]]
Accuracy score for KNN 0.42857142857142855


In [202]:
#Cross Validation
scores = cross_val_score(classifier, x_train, y_train, cv=3)
print(" Accuracy score for KNN using 10-fold cross validation: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

 Accuracy score for KNN using 10-fold cross validation: 0.56 (+/- 0.27)
